### PR TITLE
Alltoall

### PR DESCRIPTION
**Pull request by saeedmaleki**
Made the changes to an empty alltoall call. Please review the code changes!

### CODE REVIEW

**Review by madanMus — APPROVED** [review]
LGTM

**Comment by olsaarik** [comment]
Will these stubs be filled in with a concrete implementation, or will we use this as a target template for SCKL?

**Comment by saeedmaleki** [comment]
> Will these stubs be filled in with a concrete implementation, or will we use this as a target template for SCKL?

For now we wanted an empty alltoall. First step would be to fill it in with a concrete implementation for nodes with NVSwitches and later we make it generated automatically by SCKL.

**Comment by olsaarik** [comment]
Is there a baseline implementation that will work on some level for all pieces of hardware that we can fill in here later? I know there's that ncclSend/Recv between all pairs, but that actually involves multiple NCCL calls, so idk if that is easy to insert just into a single kernel call.

Basically what I'm trying to imagine is what's the user experience later on when we do have SCKL hooked in. When a user installs this augmented version of NCCL, do they have the option of not running SCKL? If so then we could have one of the following behaviors:

- The ncclAllToAll function is not present in the shared library at all.
- The ncclAllToAll function is there, but will error out.
- The ncclAllToAll function gives some (bad) baseline performance, possibly with a warning.

First one makes the bad perf a link time bug, but is probably inconvenient. Last one feels best to me likely.

**Review by olsaarik — APPROVED** [review]

**Comment by saeedmaleki** [comment]
> Is there a baseline implementation that will work on some level for all pieces of hardware that we can fill in here later? I know there's that ncclSend/Recv between all pairs, but that actually involves multiple NCCL calls, so idk if that is easy to insert just into a single kernel call.
> 
> Basically what I'm trying to imagine is what's the user experience later on when we do have SCKL hooked in. When a user installs this augmented version of NCCL, do they have the option of not running SCKL? If so then we could have one of the following behaviors:
> 
> * The ncclAllToAll function is not present in the shared library at all.
> * The ncclAllToAll function is there, but will error out.
> * The ncclAllToAll function gives some (bad) baseline performance, possibly with a warning.
> 
> First one makes the bad perf a link time bug, but is probably inconvenient. Last one feels best to me likely.

This is a great point. The initial thought is to have a dumb implementation with all pairs of connections. At the bootstrap, we will check if the connections can be made. If not, exit with warning and report that a naive ncclSend and ncclRecv needs to be used instead. This will be the first version we can handout to users with NVSwitch machines.

**Pull request merged**
